### ISSUE TITLE
MIUI 8 (Android 5.0.2) 安装至 /system 仍出现 need INSTALL_LOCATION_PROVIDER 错误

### ISSUE THREAD

**Issue by Honghe** [xiangtailiang/FakeGPS#8]
错误详情

```
 E/LocationThread: add Location fail!
   java.lang.SecurityException: need INSTALL_LOCATION_PROVIDER permission, or UID of a currently bound location provider
       at android.os.Parcel.readException(Parcel.java:1540)
       at android.os.Parcel.readException(Parcel.java:1493)
       at android.location.ILocationManager$Stub$Proxy.reportLocation(ILocationManager.java:1240)
       at com.github.fakegps.LocationThread$1.run(LocationThread.java:134)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:135)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

另一台三星4.3运行正常。

**Comment by xiangtailiang** [comment]
MIUI的修改了Android原生的权限，更严格了。导致FakeGps获取不了权限。
